# Generated by Django 2.2.13 on 2020-08-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'ADULTO'), ('T', 'TEENS'), ('K', 'KIDS'), ('B', 'BABY')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marca_produtos', to='produtos.Marca'),
        ),
    ]
