# Generated by Django 2.2.13 on 2020-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200806_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(max_length=2),
        ),
    ]
