# Generated by Django 2.2.13 on 2020-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20200806_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(max_length=2, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'ADULTO'), ('T', 'TEENS'), ('K', 'KIDS'), ('B', 'BABY')], max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
