# Generated by Django 2.2.13 on 2020-08-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20200806_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(max_length=3, verbose_name='Tamanho'),
        ),
    ]
