# Generated by Django 2.2.13 on 2020-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_estoque_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
    ]
