# Generated by Django 2.2.13 on 2020-08-31 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0023_auto_20200801_2107'),
        ('produtos', '0007_produto_estoque_min'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('desconto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Desconto')),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Final')),
                ('forma_pagamento', models.PositiveIntegerField(choices=[(0, 'Dinheiro'), (1, 'Credito'), (2, 'Debito'), (3, 'Carnê')], verbose_name='Forma de Pagamento')),
                ('qtd_parcelas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas')),
                ('valor_parcelas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor das Parcelas')),
                ('venc_parcelas', models.DateField(blank=True, null=True, verbose_name='Vencimento das Parcelas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.Cliente')),
                ('produtos', models.ManyToManyField(through='vendas.ItemVenda', to='produtos.Produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda'),
        ),
    ]
