# Generated by Django 2.2.13 on 2020-08-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Dinheiro'), (1, 'Credito'), (2, 'Debito'), (3, 'Carnê')], verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Preço Final'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
