# Generated by Django 2.2.13 on 2020-06-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200615_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VENDEDOR'), (2, 'CAIXA'), (3, 'SUPERVISOR'), (4, 'ADMINISTRADOR')], default=1),
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
    ]
