# Generated by Django 2.2.13 on 2020-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20200615_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], max_length=1),
        ),
    ]
