# Generated by Django 2.2.13 on 2020-07-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20200723_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
