# Generated by Django 2.2.13 on 2020-07-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20200727_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
