# Generated by Django 2.2.13 on 2020-06-14 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.IntegerField(choices=[(1, 'FEMININO'), (2, 'MASCULINO')])),
                ('data_nasc', models.DateField()),
                ('fone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('estado_civil', models.IntegerField(choices=[(1, 'CASADO(A)'), (2, 'DIVORCIADO(A)'), (3, 'SEPARADO(A)'), (4, 'SOLTEIRO(A)'), (5, 'VIUVO(A)')])),
                ('conjuge', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=50)),
                ('filiacao', models.CharField(max_length=100)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('obs', models.TextField()),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
