# Generated by Django 2.2.13 on 2020-06-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200614_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='end_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos_entregas', to='clientes.Endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos', to='clientes.Endereco'),
        ),
    ]
