# Generated by Django 2.2.13 on 2020-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200730_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ATIVO'), (2, 'SPC'), (3, 'SUSPENSO'), (4, 'IMPRESSO')], default=1),
        ),
    ]
