# Generated by Django 2.2.13 on 2020-07-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_cliente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fone_recado',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
