# Generated by Django 2.2.13 on 2020-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20200730_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='filiacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
