# Generated by Django 2.2.13 on 2020-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20200731_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ativo',
            field=models.BooleanField(),
        ),
    ]
