# Generated by Django 2.2.13 on 2020-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20200731_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
