# Generated by Django 2.2.13 on 2020-08-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_auto_20200801_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='endereco',
            new_name='logradouro',
        ),
    ]
