# Generated by Django 2.2.13 on 2020-08-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_auto_20200801_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
